### ISSUE TITLE
Illegal ObjectID in query causes unhandled exception

### ISSUE THREAD

**Issue by blalor** [vert-x/mod-mongo-persistor#21]
Vert.x 1.3.1.final, mod-mongo-persistor 1.2.1

Performing a query for an object with an illegal ObjectID causes an exception which is not reported back to the caller.

The following query causes the stack trace below:
```json
{
    "action": "findone",
    "collection": "users",
    "matcher": {
        "$or": [
            { "_id": "_Seed_User_Id" },
            {
                "_id": { "$oid": "_Seed_User_Id" }
            }
        ]
    }
}
```

```
2013-03-21 10:48:34,457 [vert.x-worker-thread-12] ERROR org.vertx.deployments.deployment-e70ccff7-f5b0-41d9-9e73-bf0128061843-0 - Exception in Java verticle script
java.lang.IllegalArgumentException: invalid ObjectId [_Seed_User_Id]
	at org.bson.types.ObjectId.<init>(ObjectId.java:128)
	at org.bson.types.ObjectId.<init>(ObjectId.java:122)
	at com.mongodb.util.JSONCallback.objectDone(JSONCallback.java:69)
	at com.mongodb.util.JSONParser.parseObject(JSON.java:243)
	at com.mongodb.util.JSONParser.parse(JSON.java:195)
	at com.mongodb.util.JSONParser.parseObject(JSON.java:231)
	at com.mongodb.util.JSONParser.parse(JSON.java:195)
	at com.mongodb.util.JSONParser.parseArray(JSON.java:539)
	at com.mongodb.util.JSONParser.parse(JSON.java:191)
	at com.mongodb.util.JSONParser.parseObject(JSON.java:231)
	at com.mongodb.util.JSONParser.parse(JSON.java:195)
	at com.mongodb.util.JSONParser.parse(JSON.java:145)
	at com.mongodb.util.JSON.parse(JSON.java:81)
	at com.mongodb.util.JSON.parse(JSON.java:66)
	at org.vertx.mods.MongoPersistor.jsonToDBObject(MongoPersistor.java:415)
	at org.vertx.mods.MongoPersistor.doFindOne(MongoPersistor.java:325)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:103)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:45)
	[…]
```

`Message#reply()` is never invoked, so the caller is never given a response.

**Comment by karianna** [comment]
@blalor - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
