### ISSUE TITLE
New JsonObject <--> BSON broke date support

### ISSUE THREAD

**Issue by Kazaag** [vert-x/mod-mongo-persistor#53]
The change in the way the transformation from and to Vertx Json and BSON is done, make date handling impossible.

The map strategy break the custom $ handling of Mongo Json.  It is mo more possible to define a date file using this object { "dateField": {"$date" : 1454884}}; this will trigger an error as the field can't have a name starting by $.

Reading a document with a date field is now impossible.  The BSON to JsonNode transformation won't be able to handle the Date object in the BSON Map; the stack trace follows:

org.vertx.java.core.VertxException: Cannot have objects of class class java.util.Date in JSON
	at org.vertx.java.core.json.JsonElement.convertMap(JsonElement.java:60)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:56)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:45)
	at org.vertx.mods.MongoPersistor.doFindOne(MongoPersistor.java:398)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:146)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:41)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:943)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Having the possibility to provide Json that is interpreted by the Mongo part as there custom JSON serialization of BSON, allows to have more control on the actual BSON.

As the new transformation break existing code and prevent to retrieve preexisting data, the Json serialization transformation should be the default one.

**Comment by xunitc** [comment]
I do something, only let it work.
At the line MongoPersistor.java:409 :
      //JsonObject m = new JsonObject(res.toMap());
      //reply.putObject("result", m);
      Gson gson = new Gson();
      reply.putObject("result", new JsonObject(gson.toJson(res.toMap())));

And in build.gradle:
dependencies {
  //others
  compile "com.google.code.gson:gson:2.3.1"
}

I guess the org.vertx.java.core.json.JsonObject sometimes can not convert some object type, only my guess.

**Comment by karianna** [comment]
@Kazaag - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
