### ISSUE TITLE
find-and-modify with upsert:true fails due to ObjectId

### ISSUE THREAD

**Issue by rhoegg** [vert-x/mod-mongo-persistor#66]
When I use find-and-modify with upsert:true to create a document, it fails with the following exception:
```
org.vertx.java.core.VertxException: Cannot have objects of class class org.bson.types.ObjectId in JSON
	at org.vertx.java.core.json.JsonElement.convertMap(JsonElement.java:60)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:56)
	at org.vertx.java.core.json.JsonObject.<init>(JsonObject.java:45)
	at org.vertx.mods.MongoPersistor.doFindAndModify(MongoPersistor.java:431)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:153)
	at org.vertx.mods.MongoPersistor.handle(MongoPersistor.java:41)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
This occurs because Mongo creates the document and we did not provide an _id field.  This is my normal use case, as I would just use update if I had the _id already.

**Comment by karianna** [comment]
@rhoegg - We've moved to the new vert-x3 project with an all new MongoClient https://github.com/vert-x3/vertx-mongo-client
